// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Session struct {
	ID        int64        `db:"id"`
	UserID    int64        `db:"user_id"`
	Token     string       `db:"token"`
	CreatedAt sql.NullTime `db:"created_at"`
}

type User struct {
	ID        int64        `db:"id"`
	Username  string       `db:"username"`
	Password  string       `db:"password"`
	CreatedAt sql.NullTime `db:"created_at"`
}
