// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/benciks/flow-backend/internal/database/db"
)

type Mutation struct {
}

type Query struct {
}

type SignInPayload struct {
	Token string   `json:"token"`
	User  *db.User `json:"user"`
}

type Task struct {
	ID          int      `json:"id"`
	Description string   `json:"description"`
	Entry       string   `json:"entry"`
	Modified    string   `json:"modified"`
	UUID        string   `json:"uuid"`
	Urgency     float64  `json:"urgency"`
	Status      string   `json:"status"`
	Priority    string   `json:"priority"`
	Due         string   `json:"due"`
	Project     string   `json:"project"`
	Tags        []string `json:"tags"`
}

type TimeRecord struct {
	ID    int      `json:"id"`
	Start string   `json:"start"`
	End   string   `json:"end"`
	Tags  []string `json:"tags"`
}
