// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TimeRecord struct {
	ID    string   `json:"id"`
	Start string   `json:"start"`
	End   string   `json:"end"`
	Tags  []string `json:"tags"`
}
