package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
	"strconv"

	"github.com/benciks/flow-backend/internal/graph/model"
)

// TimeStart is the resolver for the timeStart field.
func (r *mutationResolver) TimeStart(ctx context.Context) (*model.TimeRecord, error) {
	cmd, err := exec.Command("timew", "start").Output()
	if err != nil {
		return nil, err
	}

	cmd, err = exec.Command("timew", "export", "@1").Output()
	if err != nil {
		return nil, err
	}

	var timeRecord []TimeExport
	err = json.Unmarshal(cmd, &timeRecord)

	return &model.TimeRecord{
		ID:    "0",
		Start: timeRecord[0].Start,
		End:   timeRecord[0].End,
		Tags:  timeRecord[0].Tags,
	}, nil
}

// TimeStop is the resolver for the timeStop field.
func (r *mutationResolver) TimeStop(ctx context.Context) (*model.TimeRecord, error) {
	cmd, err := exec.Command("timew", "stop").Output()
	if err != nil {
		return nil, err
	}

	cmd, err = exec.Command("timew", "export", "@1").Output()
	if err != nil {
		return nil, err
	}

	var timeRecord []TimeExport
	err = json.Unmarshal(cmd, &timeRecord)

	return &model.TimeRecord{
		ID:    "0",
		Start: timeRecord[0].Start,
		End:   timeRecord[0].End,
		Tags:  timeRecord[0].Tags,
	}, nil
}

// DeleteTimeRecord is the resolver for the deleteTimeRecord field.
func (r *mutationResolver) DeleteTimeRecord(ctx context.Context, id string) (*model.TimeRecord, error) {
	// First get the time record to be deleted
	cmd, err := exec.Command("timew", "export", "@"+id).Output()
	if err != nil {
		return nil, err
	}

	var timeRecord []TimeExport
	err = json.Unmarshal(cmd, &timeRecord)

	// Then delete it
	cmd, err = exec.Command("timew", "delete", "@"+id).Output()
	if err != nil {
		return nil, err
	}

	return &model.TimeRecord{
		ID:    "-1",
		Start: timeRecord[0].Start,
		End:   timeRecord[0].End,
		Tags:  timeRecord[0].Tags,
	}, nil
}

// ModifyTimeRecordDate is the resolver for the modifyTimeRecordDate field.
func (r *mutationResolver) ModifyTimeRecordDate(ctx context.Context, id string, start *string, end *string) (*model.TimeRecord, error) {
	if start == nil && end == nil {
		return nil, fmt.Errorf("both start and end cannot be nil")
	}

	if start != nil {
		_, err := exec.Command("timew", "modify", "start", "@"+id, *start).Output()
		if err != nil {
			return nil, err
		}
	}

	if end != nil {
		_, err := exec.Command("timew", "modify", "end", "@"+id, *end).Output()
		if err != nil {
			return nil, err
		}
	}

	cmd, err := exec.Command("timew", "export", "@"+id).Output()
	if err != nil {
		return nil, err
	}

	var timeRecord []TimeExport
	err = json.Unmarshal(cmd, &timeRecord)

	return &model.TimeRecord{
		ID:    id,
		Start: timeRecord[0].Start,
		End:   timeRecord[0].End,
		Tags:  timeRecord[0].Tags,
	}, nil
}

// TagTimeRecord is the resolver for the tagTimeRecord field.
func (r *mutationResolver) TagTimeRecord(ctx context.Context, id string, tag string) (*model.TimeRecord, error) {
	cmd, err := exec.Command("timew", "tag", "@"+id, tag).Output()
	if err != nil {
		return nil, err
	}

	cmd, err = exec.Command("timew", "export", "@"+id).Output()
	if err != nil {
		return nil, err
	}

	var timeRecord []TimeExport
	err = json.Unmarshal(cmd, &timeRecord)

	return &model.TimeRecord{
		ID:    id,
		Start: timeRecord[0].Start,
		End:   timeRecord[0].End,
		Tags:  timeRecord[0].Tags,
	}, nil
}

// UntagTimeRecord is the resolver for the untagTimeRecord field.
func (r *mutationResolver) UntagTimeRecord(ctx context.Context, id string, tag string) (*model.TimeRecord, error) {
	cmd, err := exec.Command("timew", "untag", "@"+id, tag).Output()
	if err != nil {
		return nil, err
	}

	cmd, err = exec.Command("timew", "export", "@"+id).Output()
	if err != nil {
		return nil, err
	}

	var timeRecord []TimeExport
	err = json.Unmarshal(cmd, &timeRecord)

	return &model.TimeRecord{
		ID:    id,
		Start: timeRecord[0].Start,
		End:   timeRecord[0].End,
		Tags:  timeRecord[0].Tags,
	}, nil
}

// TimeRecords is the resolver for the timeRecords field.
func (r *queryResolver) TimeRecords(ctx context.Context) ([]*model.TimeRecord, error) {
	cmd, err := exec.Command("timew", "export").Output()
	if err != nil {
		return nil, err
	}

	type Export struct {
		Id    int
		Start string
		End   string
		Tags  []string
	}

	var timeRecords []Export
	err = json.Unmarshal(cmd, &timeRecords)

	var timeRecordsModel []*model.TimeRecord
	for _, timeRecord := range timeRecords {
		timeRecordsModel = append(timeRecordsModel, &model.TimeRecord{
			ID:    strconv.Itoa(timeRecord.Id),
			Start: timeRecord.Start,
			End:   timeRecord.End,
			Tags:  timeRecord.Tags,
		})
	}

	// Reverse the order of the time records
	for i, j := 0, len(timeRecordsModel)-1; i < j; i, j = i+1, j-1 {
		timeRecordsModel[i], timeRecordsModel[j] = timeRecordsModel[j], timeRecordsModel[i]
	}

	return timeRecordsModel, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
type TimeExport struct {
	Id    int
	Start string
	End   string
	Tags  []string
}
